# This file was generated by GoReleaser. DO NOT EDIT.
class Rare < Formula
  desc "Fast, realtime regex-extraction, and aggregation into common formats such as histograms, numerical summaries, tables, and more!"
  homepage "https://github.com/zix99/rare"
  version "0.1.26"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zix99/rare/releases/download/0.1.26/rare_0.1.26_Darwin_x86_64.tar.gz"
    sha256 "597a73a5f5b6804b54b6a8158aa920308477d7d06178344537aa803e06163924"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/zix99/rare/releases/download/0.1.26/rare_0.1.26_Linux_x86_64.tar.gz"
      sha256 "cd82cf3c41b8424a488ffa63d99eb518af7d750f1cd926e68ed2b4e5a36a99d7"
    end
  end

  def install
    bin.install "rare"
  end

  test do
    system "#{bin}/rare -v"
  end
end
