# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rare < Formula
  desc "Fast, realtime regex-extraction, and aggregation into common formats such as histograms, numerical summaries, tables, and more!"
  homepage "https://github.com/zix99/rare"
  version "0.4.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zix99/rare/releases/download/0.4.2/rare_0.4.2_Darwin_x86_64.tar.gz"
      sha256 "8b276d3ded16a752c264747b501b602321c6cb9cf92ed586620cfc8d6ae1a065"

      def install
        bin.install "rare"
        man1.install Dir["rare.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zix99/rare/releases/download/0.4.2/rare_0.4.2_Darwin_arm64.tar.gz"
      sha256 "5184de6703d2f019939483c241f8ecc5280d178219b7c378ed5f747c1ec08d05"

      def install
        bin.install "rare"
        man1.install Dir["rare.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zix99/rare/releases/download/0.4.2/rare_0.4.2_Linux_x86_64.tar.gz"
        sha256 "97af206ff59c27552faf442774b07d42d2e33a9facc9c1295f731fc555218170"

        def install
          bin.install "rare"
          man1.install Dir["rare.1.gz"]
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zix99/rare/releases/download/0.4.2/rare_0.4.2_Linux_arm64.tar.gz"
        sha256 "6fb18c59c97950660cc987b3ccf3d47f21d0815824d58fb9c04d27153691f6be"

        def install
          bin.install "rare"
          man1.install Dir["rare.1.gz"]
        end
      end
    end
  end

  test do
    system "#{bin}/rare -v"
  end
end
